language: python
cache: pip
jobs:
  include:
  - stage: osx-deploy
    language: shell
    osx_image: xcode11.2 # Python 3.7.4 running on macOS 10.14.4
    os: osx
    before_install: skip
    script:  # no tests
      - go version
      - python3 --version
      - make build_helm_binding
      - make test
    after_success: true  # overwrite after_success and do nothing
    after_deploy: skip

before_install:
  # Loop until update succeeds (timeouts can occur)
  - sudo sed -e '/postgresql/ s/^#*/#/' -i /etc/apt/sources.list.d/*
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
  - sudo add-apt-repository ppa:longsleep/golang-backports -y
  # workaround for https://travis-ci.community/t/then-sudo-apt-get-update-failed-public-key-is-not-available-no-pubkey-6b05f25d762e3157-in-ubuntu-xenial/1728
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 762E3157
  # Loop until update succeeds (timeouts can occur)
  - travis_retry $(! sudo apt-get -qq update 2>&1 | grep Failed)
  - sudo apt-get install -y g++-4.9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  - sudo apt-get install -y gnupg2 git
  - sudo apt-get install -y golang-1.12
  - export PATH="/usr/lib/go-1.12/bin:$PATH"
  - export GOROOT=/usr/lib/go-1.12
  - go version

install:
  - pip3 install -r requirements.txt
  - pip3 install coverage

script:
  - make build_helm_binding
  - make test && make test_coverage
  - make build_binary
  - make test_binary
