language: python
cache:
  directories:
    - ~/Library/Caches/pip

jobs:
  include:
  - stage: osx-deploy
    language: shell
    osx_image: xcode11.2 # Python 3.7.4 running on macOS 10.14.4
    os: osx
    before_install: skip
    script:  # no tests
      - go version
      - python3 --version
      - make build_helm_binding
      - python3 -m unittest tests.test_helm_input
    after_success: true  # overwrite after_success and do nothing
    after_deploy: skip

install:
  - pip3 install -r requirements.txt
  - pip3 install coverage

script:
  - make build_helm_binding
  - make test && make test_coverage
  - make build_binary
  - make test_binary
