language: python
cache:
  directories:
    - ~/Library/Caches/pip

jobs:
  include:
  - stage: osx-deploy
    language: shell
    osx_image: xcode10.2 # Python 3.7.2, go 1.12.4
    os: osx
    before_install: skip
    script:  # no tests
      - go version
      - python3 --version
      - make build_helm_binding
      - python3 -m unittest tests.test_helm_input.HelmInputTest.test_compile_subcharts
    after_success: true  # overwrite after_success and do nothing
    after_deploy: skip

install:
  - pip3 install -r requirements.txt

